using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ItemProcessingSystem.Models
{
    /// <summary>
    /// Represents an item that can be processed into child items.
    /// Uses a self-referencing relationship (ParentId) to form a tree hierarchy.
    /// </summary>
    public class Item
    {
        // Primary key - auto-generated by the database
        [Key]
        public int Id { get; set; }

        // Name of the item
        [Required(ErrorMessage = "Item name is required.")]
        [StringLength(200, ErrorMessage = "Item name cannot exceed 200 characters.")]
        [Display(Name = "Item Name")]
        public string Name { get; set; } = string.Empty;

        // Weight of the item - must be a positive number
        [Required(ErrorMessage = "Weight is required.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Weight must be a positive number.")]
        [Display(Name = "Weight")]
        public decimal Weight { get; set; }

        // Foreign key - references the parent item (null for root items)
        [Display(Name = "Parent Item")]
        public int? ParentId { get; set; }

        // Indicates whether this item has been processed into child items
        [Display(Name = "Is Processed")]
        public bool IsProcessed { get; set; } = false;

        // Timestamp when the item was created
        [Display(Name = "Created Date")]
        public DateTime CreatedDate { get; set; } = DateTime.Now;

        // ==========================================
        // Navigation Properties (for EF Core)
        // ==========================================

        /// <summary>
        /// Navigation property to the parent item.
        /// Null for root-level items (items with no parent).
        /// EF Core uses ForeignKey attribute to link ParentId to this property.
        /// </summary>
        [ForeignKey("ParentId")]
        public virtual Item? Parent { get; set; }

        /// <summary>
        /// Collection of child items that were created by processing this item.
        /// InverseProperty tells EF Core that this collection is the "other side"
        /// of the Parent navigation property (avoiding ambiguity in self-referencing).
        /// </summary>
        [InverseProperty("Parent")]
        public virtual ICollection<Item> ChildItems { get; set; } = new List<Item>();
    }
}
