using System.ComponentModel.DataAnnotations;

namespace ItemProcessingSystem.Models
{
    /// <summary>
    /// Represents a user who can login and manage items in the system.
    /// </summary>
    public class User
    {
        // Primary key - auto-generated by the database
        [Key]
        public int Id { get; set; }

        // User's email address - used for login
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address.")]
        [StringLength(100, ErrorMessage = "Email cannot exceed 100 characters.")]
        public string Email { get; set; } = string.Empty;

        // User's password - stored as plain text for simplicity
        // In production, this should be hashed
        [Required(ErrorMessage = "Password is required.")]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Password must be between 6 and 100 characters.")]
        [DataType(DataType.Password)]
        public string Password { get; set; } = string.Empty;

        // Timestamp when the user was created
        public DateTime CreatedDate { get; set; } = DateTime.Now;
    }
}
